pub mod app_lifecycle;
pub mod auth_webview;
pub mod autostart;
pub mod browser_extension;
pub mod clip;
pub mod diagnostics;
pub mod downloads;
pub mod extension_cookies;
pub mod host_queue;
pub mod integration;
pub mod p2p;
pub mod plugins;
pub mod reencode;
pub mod rpc;
pub mod settings;
pub mod yt_templates;

#[cfg(not(target_os = "android"))]
pub mod dependencies;
#[cfg(not(target_os = "android"))]
pub mod quark;
#[cfg(not(target_os = "android"))]
pub mod search;
